version: '3.8'

services:
  daily-quotes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily-quotes-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - daily-quotes
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  jenkins-data:
  docker-sock:

