# Docker testing configuration for Selenium tests
version: '3.8'

services:
  # Selenium Hub and Chrome nodes
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4445:4445"
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300

  chrome-node:
    image: selenium/node-chrome:4.15.0
    container_name: chrome-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=4
      - NODE_MAX_SESSION=4

  # Application container
  daily-quotes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily-quotes-app
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Test runner
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: test-runner
    depends_on:
      - selenium-hub
      - chrome-node
      - daily-quotes
    environment:
      - SELENIUM_HUB=http://selenium-hub:4444
      - APP_URL=http://daily-quotes:3000
      - TEST_TYPE=integration
    volumes:
      - ./tests:/app/tests
      - ./test-results:/app/test-results
    command: npm run test:selenium

